model:
  name: "rawgat_st"
  checkpoint_path: ""
  parameters:
    nb_samp: 64_600
    out_channels: 70
    first_conv: 128
    in_channels: 1
    filts: [32, [32, 32], [32, 64], [64, 64]]
    blocks: [2, 4]
    nb_classes: 1


